# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-27 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('locname', models.CharField(max_length=200, verbose_name='LocationName')),
                ('myname', models.CharField(max_length=200, verbose_name='My Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, default=0, null=True)),
                ('lng', models.FloatField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
