# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0002_auto_20180301_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='slugurl',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
