# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0003_position_slugurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='position',
            name='slugurl',
            field=models.SlugField(allow_unicode=True, default='1', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
    ]
