# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0004_auto_20180302_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='slugurl',
            new_name='slug',
        ),
    ]
