# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0005_auto_20180302_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
