# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0006_auto_20180303_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
