# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0007_position_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
