# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0009_auto_20180306_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(max_length=300, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='locname',
            field=models.CharField(max_length=300, verbose_name='LocationName'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=300, verbose_name='My Name'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
