# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0010_auto_20180306_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
