# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onmap', '0012_position_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='ptype',
            field=models.CharField(default='E', max_length=1, verbose_name='Type'),
        ),
    ]
